"""
Django settings for CLAS project.

Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path
import os  # Added for environment variable usage if needed later

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d7-y*7dh!m+f1zu=tb%vg%*rgfn4sbt93klb-g1is4li41c&qk'

# SECURITY WARNING: don't run with debug turned on in production!
# You usually want this False in production, but keep True for now to see errors
DEBUG = True 

# ✅ UPDATED: Allow all hosts so Render can serve the app
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'class',
    'widget_tweaks',
     "tailwind",
    "theme",
    "django_browser_reload",
    'django.contrib.humanize',  # For better number formatting
]
# Tailwind CSS Configuration
TAILWIND_APP_NAME = "theme"

# Tailwind CSS optimization settings
TAILWIND_CSS_DEV_MODE = DEBUG  # Use development mode only when DEBUG is True

# Additional Tailwind settings for performance
if not DEBUG:
    # Production optimizations
    TAILWIND_CSS_PURGE = True
    TAILWIND_CSS_MINIFY = True
else:
    # Development optimizations
    TAILWIND_CSS_PURGE = False
    TAILWIND_CSS_MINIFY = False

# Static files optimization
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Enable static file compression in production
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
    # Additional compression settings
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = False
    WHITENOISE_SKIP_COMPRESS_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'gz', 'tgz', 'bz2', 'tbz', 'xz', 'br']
else:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # ✅ DATABASE CONNECTION HANDLING (FIRST - before other middleware)
    'class.db_connection_middleware.DatabaseConnectionMiddleware',
    # ✅ SESSION MANAGEMENT (NO TIMEOUT - USERS STAY LOGGED IN)
    'class.services.session_auth_fix.LocalStorageCleanupMiddleware',
    'class.services.session_auth_fix.URLAccessControlMiddleware',
    # Performance optimization
    'class.performance_middleware.PerformanceOptimizationMiddleware',
    'class.performance_middleware.BrowserCachingMiddleware',
    'class.performance_middleware.ResponseCompressionMiddleware',
    # Error handling
    'class.session_timeout_middleware.UserFriendlyErrorMiddleware',
    'class.middleware.MessageCleanupMiddleware',
    'class.middleware.DebugMessageSuppressMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CLAS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CLAS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'neondb',
        'USER': 'neondb_owner',
        'PASSWORD': 'npg_ICyqflMD5ma7',
        'HOST': 'ep-flat-water-aeh2db45.c-2.us-east-2.aws.neon.tech',
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require',
            'connect_timeout': 10,
            'options': '-c statement_timeout=30000'  # 30 second timeout
        },
        'CONN_MAX_AGE': 0,  # ✅ FIXED: Don't reuse connections (was 600)
        'CONN_HEALTH_CHECKS': True,  # Enable connection health checks
        'AUTOCOMMIT': True,  # Auto-commit transactions
    }
}

# ===== PERFORMANCE OPTIMIZATIONS =====

# Caching Configuration - Optimized for Performance
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 600,  # 10 minutes default timeout
        'OPTIONS': {
            'MAX_ENTRIES': 2000,  # Increased for better caching
            'CULL_FREQUENCY': 3,
        }
    },
    'sessions': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'session-cache',
        'TIMEOUT': 7200,  # 2 hours for sessions
    },
    'curriculum': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'curriculum-cache',
        'TIMEOUT': 7200,  # 2 hours for curriculum content
    },
    'dashboard': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'dashboard-cache',
        'TIMEOUT': 300,  # 5 minutes for dashboard stats
    }
}

# Cache middleware settings - Optimized
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 600  # 10 minutes for page caching

# HTTP Cache Headers for static files
CACHE_CONTROL_MAX_AGE = 31536000  # 1 year for static files
CACHE_MIDDLEWARE_KEY_PREFIX = 'clas'

# Session Configuration for Performance
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'sessions'
SESSION_COOKIE_AGE = 31536000  # 1 year (keep users logged in)
SESSION_SAVE_EVERY_REQUEST = False  # Only save when modified (better performance)
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection

# Session timeout configuration (in seconds)
SESSION_TIMEOUT = 31536000  # 1 year - keep users logged in
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Sessions persist after browser closes

# Database Query Optimization
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging Configuration for Performance Monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'class': {  # Your app logger
            'handlers': ['file', 'console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': True,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static", 
]




# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'class.User'
