# Generated by Django 6.0 on 2025-12-13 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_user_groups_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('udise', models.CharField(max_length=50, unique=True)),
                ('block', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
                ('enrolled_students', models.IntegerField(default=0)),
                ('avg_attendance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('validation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='schools/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
