# Generated by Django 5.1.15 on 2025-12-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_classsection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classsection',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=9),
        ),
        migrations.AddField(
            model_name='classsection',
            name='display_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='classsection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together={('school', 'class_level', 'section', 'academic_year')},
        ),
    ]
