# Generated by Django 5.1.15 on 2025-12-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0005_alter_classsection_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='school',
            name='enrolled_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
