# Generated by Django 5.1.15 on 2025-12-17 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0006_alter_school_options_alter_school_enrolled_students_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__id': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class.role'),
        ),
        migrations.CreateModel(
            name='FacilitatorSchool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilitator', models.ForeignKey(limit_choices_to={'role_id': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_schools', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitators', to='class.school')),
            ],
            options={
                'verbose_name': 'Facilitator–School Mapping',
                'verbose_name_plural': 'Facilitator–School Mappings',
                'unique_together': {('facilitator', 'school')},
            },
        ),
    ]
