# Generated by Django 5.1.15 on 2025-12-20 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0007_alter_user_options_user_supervisor_alter_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.classsection')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.student')),
            ],
            options={
                'unique_together': {('student', 'school', 'class_section')},
            },
        ),
    ]
