# Generated by Django 5.1.15 on 2025-12-24 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0008_student_enrollment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'class_section')},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='class.classsection'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='class.student'),
        ),
        migrations.CreateModel(
            name='PlannedSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('youtube_url', models.URLField(help_text='YouTube video URL for this session')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_sessions', to='class.classsection')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('class_section', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ActualSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('conducted', 'Conducted'), ('holiday', 'Holiday'), ('cancelled', 'Cancelled')], default='conducted', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_sessions', to=settings.AUTH_USER_MODEL)),
                ('planned_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_sessions', to='class.plannedsession')),
            ],
            options={
                'unique_together': {('planned_session', 'date')},
            },
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='school',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('actual_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='class.actualsession')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.enrollment')),
            ],
            options={
                'unique_together': {('actual_session', 'enrollment')},
            },
        ),
    ]
