# Generated by Django 5.1.15 on 2025-12-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0009_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='class.school'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'school', 'class_section')},
        ),
    ]
