# Generated by Django 5.1.15 on 2025-12-29 17:09

from django.db import migrations


def populate_enrollment_school(apps, schema_editor):
    """Populate school field in existing enrollments from class_section"""
    Enrollment = apps.get_model('class', 'Enrollment')
    
    for enrollment in Enrollment.objects.select_related('class_section__school').all():
        if not enrollment.school and enrollment.class_section:
            enrollment.school = enrollment.class_section.school
            enrollment.save()


def reverse_populate_enrollment_school(apps, schema_editor):
    """Reverse migration - clear school field"""
    Enrollment = apps.get_model('class', 'Enrollment')
    Enrollment.objects.update(school=None)


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0010_alter_enrollment_unique_together_enrollment_school_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_enrollment_school, reverse_populate_enrollment_school),
    ]
