# Generated by Django 5.1.15 on 2025-12-29 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0011_auto_20251229_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='class.school'),
        ),
    ]
