# Generated by Django 5.1.15 on 2026-01-04 05:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0012_alter_enrollment_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannedsession',
            old_name='topic',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='plannedsession',
            name='youtube_url',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'class_section', 'is_active')},
        ),
        migrations.CreateModel(
            name='SessionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('subject', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('maths', 'Maths'), ('computer', 'Computer'), ('activity', 'Activity'), ('mindfulness', 'Mindfulness')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('planned_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='class.plannedsession')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('planned_session', 'order')},
            },
        ),
    ]
