# Generated by Django 5.1.15 on 2026-01-04 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0013_rename_topic_plannedsession_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualsession',
            options={'verbose_name': 'Actual Session', 'verbose_name_plural': 'Actual Sessions'},
        ),
        migrations.AlterModelOptions(
            name='plannedsession',
            options={'ordering': ['day_number'], 'verbose_name': 'Planned Session (Day)', 'verbose_name_plural': 'Planned Sessions (Days)'},
        ),
        migrations.AlterModelOptions(
            name='sessionstep',
            options={'ordering': ['order'], 'verbose_name': 'Session Step', 'verbose_name_plural': 'Session Steps'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='class.enrollment'),
        ),
        migrations.AlterField(
            model_name='plannedsession',
            name='day_number',
            field=models.PositiveIntegerField(help_text='Logical day number (Day 1, Day 2, ...)'),
        ),
        migrations.AlterField(
            model_name='plannedsession',
            name='description',
            field=models.TextField(blank=True, help_text='Optional day-level description'),
        ),
        migrations.AlterField(
            model_name='plannedsession',
            name='title',
            field=models.CharField(help_text='Session title (e.g. CLAS - Computer Literacy At School)', max_length=255),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed teacher instructions'),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='order',
            field=models.PositiveIntegerField(help_text='Execution order inside the day (1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='subject',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('maths', 'Maths'), ('computer', 'Computer'), ('activity', 'Activity / Energizer'), ('mindfulness', 'Mindfulness')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='title',
            field=models.CharField(help_text="Activity title (from CSV 'What' column)", max_length=255),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional YouTube video for this step', null=True),
        ),
    ]
