# Generated by Django 5.1.15 on 2026-01-04 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0014_alter_actualsession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('language', models.CharField(choices=[('hindi', 'Hindi'), ('english', 'English'), ('both', 'Both')], default='both', help_text='Target language (Hindi/English/Both)', max_length=10)),
                ('content_structure', models.JSONField(blank=True, default=dict, help_text='Template content structure')),
                ('default_activities', models.JSONField(blank=True, default=dict, help_text='Standard activities for this template')),
                ('learning_objectives', models.TextField(blank=True, help_text='Default learning objectives')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of sessions using this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session Template',
                'verbose_name_plural': 'Session Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('import_file', models.FileField(help_text='Original import file', upload_to='session_imports/')),
                ('import_timestamp', models.DateTimeField(auto_now_add=True, help_text='When import was performed')),
                ('sessions_created', models.PositiveIntegerField(default=0, help_text='Number of new sessions created')),
                ('sessions_updated', models.PositiveIntegerField(default=0, help_text='Number of existing sessions updated')),
                ('errors', models.JSONField(blank=True, default=list, help_text='Import errors and warnings')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=20)),
                ('imported_by', models.ForeignKey(help_text='Administrator who performed import', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import History',
                'verbose_name_plural': 'Import Histories',
                'ordering': ['-import_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Session title/name', max_length=255)),
                ('day_number', models.PositiveIntegerField(help_text='Day in curriculum sequence (1-150)')),
                ('language', models.CharField(choices=[('hindi', 'Hindi'), ('english', 'English')], help_text='Session language (Hindi/English)', max_length=10)),
                ('content', models.TextField(blank=True, help_text='Rich text session content')),
                ('learning_objectives', models.TextField(blank=True, help_text='Session learning goals')),
                ('activities', models.JSONField(blank=True, default=dict, help_text='Structured activity data')),
                ('resources', models.JSONField(blank=True, default=dict, help_text='Links to videos, documents, media')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Administrator who created session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Optional source template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='class.sessiontemplate')),
            ],
            options={
                'verbose_name': 'Curriculum Session',
                'verbose_name_plural': 'Curriculum Sessions',
                'ordering': ['language', 'day_number'],
                'unique_together': {('day_number', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SessionUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_timestamp', models.DateTimeField(auto_now_add=True, help_text='When session was accessed')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Time spent viewing session (seconds)', null=True)),
                ('actions', models.JSONField(blank=True, default=dict, help_text='Actions taken during session view')),
                ('facilitator', models.ForeignKey(help_text='Facilitator who accessed session', on_delete=django.db.models.deletion.CASCADE, related_name='session_accesses', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(help_text='School context of access', on_delete=django.db.models.deletion.CASCADE, related_name='session_accesses', to='class.school')),
                ('session', models.ForeignKey(help_text='Reference to accessed session', on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='class.curriculumsession')),
            ],
            options={
                'verbose_name': 'Session Usage Log',
                'verbose_name_plural': 'Session Usage Logs',
                'ordering': ['-access_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SessionVersionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('learning_objectives', models.TextField(blank=True)),
                ('activities', models.JSONField(blank=True, default=dict)),
                ('resources', models.JSONField(blank=True, default=dict)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes made in this version')),
                ('modified_by', models.ForeignKey(help_text='User who made this version', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='class.curriculumsession')),
            ],
            options={
                'verbose_name': 'Session Version History',
                'verbose_name_plural': 'Session Version Histories',
                'ordering': ['-version_number'],
                'unique_together': {('session', 'version_number')},
            },
        ),
    ]
