# Generated by Django 5.1.15 on 2026-01-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_add_curriculum_session_indexes'),
        ('class', '0015_add_curriculum_session_models'),
    ]

    operations = [
    ]
