# Generated by Django 5.1.15 on 2026-01-05 11:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0016_merge_20260104_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_date', models.DateField(auto_now_add=True, help_text='When it was uploaded')),
                ('lesson_plan_file', models.FileField(help_text='Uploaded lesson plan file', upload_to='lesson_plans/%Y/%m/')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('upload_notes', models.TextField(blank=True, help_text='Optional notes from facilitator')),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval status')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Approval timestamp', null=True)),
            ],
            options={
                'verbose_name': 'Lesson Plan Upload',
                'verbose_name_plural': 'Lesson Plan Uploads',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='SessionBulkTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Template name (e.g., 'Standard CLAS Curriculum')", max_length=255)),
                ('description', models.TextField(help_text='Template description')),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('both', 'Both')], default='english', help_text='Target language (Hindi/English/Both)', max_length=20)),
                ('total_days', models.PositiveIntegerField(default=150, help_text='Number of days in template (default 150)')),
                ('day_templates', models.JSONField(default=dict, help_text='Day-wise content templates')),
                ('default_activities', models.JSONField(default=dict, help_text='Standard activities per day')),
                ('learning_objectives', models.JSONField(default=dict, help_text='Objectives for each day')),
                ('is_active', models.BooleanField(default=True, help_text='Whether template can be used')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session Bulk Template',
                'verbose_name_plural': 'Session Bulk Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_engagement_level', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 scale')),
                ('student_understanding_level', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 scale')),
                ('student_participation_notes', models.TextField(blank=True)),
                ('learning_objectives_met', models.BooleanField(default=True)),
                ('challenging_topics', models.TextField(blank=True)),
                ('student_questions', models.TextField(blank=True)),
                ('session_completion_percentage', models.PositiveIntegerField(choices=[(0, '0%'), (10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=100, help_text='0-100%')),
                ('time_management_rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 scale')),
                ('content_difficulty_rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 scale')),
                ('facilitator_satisfaction', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1-5 scale')),
                ('what_went_well', models.TextField()),
                ('areas_for_improvement', models.TextField()),
                ('next_session_preparation', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False, help_text='Whether all required fields are filled')),
            ],
            options={
                'verbose_name': 'Session Feedback',
                'verbose_name_plural': 'Session Feedback',
                'ordering': ['-feedback_date'],
            },
        ),
        migrations.CreateModel(
            name='SessionPreparationChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_plan_reviewed', models.BooleanField(default=False)),
                ('materials_prepared', models.BooleanField(default=False)),
                ('technology_tested', models.BooleanField(default=False)),
                ('classroom_setup_ready', models.BooleanField(default=False)),
                ('student_list_reviewed', models.BooleanField(default=False)),
                ('previous_session_feedback_reviewed', models.BooleanField(default=False)),
                ('checkpoints_completed_at', models.JSONField(default=dict, help_text='Track when each checkpoint was completed')),
                ('preparation_start_time', models.DateTimeField(blank=True, null=True)),
                ('preparation_complete_time', models.DateTimeField(blank=True, null=True)),
                ('total_preparation_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('preparation_notes', models.TextField(blank=True)),
                ('anticipated_challenges', models.TextField(blank=True)),
                ('special_requirements', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Session Preparation Checklist',
                'verbose_name_plural': 'Session Preparation Checklists',
                'ordering': ['-preparation_start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reward_type', models.CharField(choices=[('photo', 'Photo'), ('text', 'Text'), ('both', 'Both')], default='text', help_text='photo, text, both', max_length=20)),
                ('reward_photo', models.ImageField(blank=True, help_text='Photo of reward/student', null=True, upload_to='session_rewards/%Y/%m/')),
                ('reward_description', models.TextField(help_text='Text description of reward')),
                ('student_names', models.TextField(help_text='Names of students who received rewards')),
                ('reward_date', models.DateTimeField(auto_now_add=True, help_text='When reward was given')),
                ('is_visible_to_admin', models.BooleanField(default=True, help_text='Admin visibility')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin comments on reward')),
            ],
            options={
                'verbose_name': 'Session Reward',
                'verbose_name_plural': 'Session Rewards',
                'ordering': ['-reward_date'],
            },
        ),
        migrations.AddField(
            model_name='actualsession',
            name='attendance_marked',
            field=models.BooleanField(default=False, help_text='Whether attendance was completed'),
        ),
        migrations.AddField(
            model_name='actualsession',
            name='can_be_rescheduled',
            field=models.BooleanField(default=True, help_text='For holiday sessions'),
        ),
        migrations.AddField(
            model_name='actualsession',
            name='cancellation_category',
            field=models.CharField(blank=True, help_text='school_shutdown, syllabus_change, exam_period, duplicate, emergency', max_length=50),
        ),
        migrations.AddField(
            model_name='actualsession',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('school_shutdown', 'School permanently shuts down for this class'), ('syllabus_change', 'Government removes topic from syllabus'), ('exam_period', 'Exam period replaces class permanently'), ('duplicate_session', 'Duplicate or wrongly created planned session'), ('emergency', 'Emergency where session will never happen again')], help_text='Predefined cancellation reasons', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actualsession',
            name='conducted_at',
            field=models.DateTimeField(blank=True, help_text='Exact time of conduct', null=True),
        ),
        migrations.AddField(
            model_name='actualsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Session duration', null=True),
        ),
        migrations.AddField(
            model_name='actualsession',
            name='is_permanent_cancellation',
            field=models.BooleanField(default=False, help_text='Cannot be undone'),
        ),
        migrations.AddField(
            model_name='actualsession',
            name='status_change_reason',
            field=models.TextField(blank=True, help_text='Why status was changed'),
        ),
        migrations.AddField(
            model_name='actualsession',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, help_text='Who changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Cannot be skipped (default True)'),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='prerequisite_days',
            field=models.JSONField(blank=True, default=list, help_text='Days that must be completed first'),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='sequence_position',
            field=models.PositiveIntegerField(blank=True, help_text='Enforced sequential position', null=True),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='actualsession',
            index=models.Index(fields=['planned_session', 'status'], name='class_actua_planned_f63c56_idx'),
        ),
        migrations.AddIndex(
            model_name='actualsession',
            index=models.Index(fields=['date', 'status'], name='class_actua_date_057acb_idx'),
        ),
        migrations.AddIndex(
            model_name='actualsession',
            index=models.Index(fields=['facilitator', 'date'], name='class_actua_facilit_6e7ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedsession',
            index=models.Index(fields=['class_section', 'day_number'], name='class_plann_class_s_4196f6_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedsession',
            index=models.Index(fields=['class_section', 'is_active'], name='class_plann_class_s_a86331_idx'),
        ),
        migrations.AddField(
            model_name='lessonplanupload',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lesson_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonplanupload',
            name='facilitator',
            field=models.ForeignKey(help_text='Who uploaded the lesson plan', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonplanupload',
            name='planned_session',
            field=models.ForeignKey(help_text='Reference to the session', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_uploads', to='class.plannedsession'),
        ),
        migrations.AddField(
            model_name='sessionbulktemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who created template', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='actual_session',
            field=models.ForeignKey(help_text='Reference to conducted session', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='class.actualsession'),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='facilitator',
            field=models.ForeignKey(help_text='Who provided feedback', on_delete=django.db.models.deletion.CASCADE, related_name='session_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionpreparationchecklist',
            name='facilitator',
            field=models.ForeignKey(help_text='Who is preparing', on_delete=django.db.models.deletion.CASCADE, related_name='preparation_checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionpreparationchecklist',
            name='planned_session',
            field=models.ForeignKey(help_text='Reference to session', on_delete=django.db.models.deletion.CASCADE, related_name='preparation_checklists', to='class.plannedsession'),
        ),
        migrations.AddField(
            model_name='sessionreward',
            name='actual_session',
            field=models.ForeignKey(help_text='Reference to the conducted session', on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='class.actualsession'),
        ),
        migrations.AddField(
            model_name='sessionreward',
            name='facilitator',
            field=models.ForeignKey(help_text='Who gave the reward', on_delete=django.db.models.deletion.CASCADE, related_name='session_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lessonplanupload',
            unique_together={('planned_session', 'facilitator')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionfeedback',
            unique_together={('actual_session', 'facilitator')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionpreparationchecklist',
            unique_together={('planned_session', 'facilitator')},
        ),
    ]
