# Generated by Django 5.1.15 on 2026-01-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0017_enhance_session_sequence_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], max_length=15),
        ),
    ]
