# Generated by Django 5.1.15 on 2026-01-05 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0018_add_leave_attendance_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_student_rating', models.FloatField(blank=True, help_text='Average session rating from students', null=True)),
                ('understanding_percentage', models.FloatField(blank=True, help_text='Percentage of students who understood the topic', null=True)),
                ('clarity_percentage', models.FloatField(blank=True, help_text='Percentage of students who found teacher clear', null=True)),
                ('student_feedback_count', models.PositiveIntegerField(default=0, help_text='Number of student feedback responses')),
                ('engagement_score', models.PositiveIntegerField(blank=True, help_text='Engagement level score (1-3)', null=True)),
                ('completion_score', models.PositiveIntegerField(blank=True, help_text='Session completion score (1-3)', null=True)),
                ('feedback_correlation_score', models.FloatField(blank=True, help_text='Correlation between student and teacher feedback', null=True)),
                ('session_quality_score', models.FloatField(blank=True, help_text='Overall session quality score', null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('actual_session', models.ForeignKey(help_text='Reference to the session', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_analytics', to='class.actualsession')),
            ],
            options={
                'verbose_name': 'Feedback Analytics',
                'verbose_name_plural': 'Feedback Analytics',
                'ordering': ['-calculated_at'],
                'unique_together': {('actual_session',)},
            },
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_student_id', models.CharField(help_text='Anonymous identifier for student', max_length=50)),
                ('session_rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rate the session (1 = Poor, 5 = Excellent)')),
                ('topic_understanding', models.CharField(choices=[('yes', 'Yes'), ('somewhat', 'Somewhat'), ('no', 'No')], help_text='Was the topic easy to understand?', max_length=20)),
                ('teacher_clarity', models.CharField(choices=[('yes', 'Yes'), ('sometimes', 'Sometimes'), ('no', 'No')], help_text='Did the teacher explain clearly?', max_length=20)),
                ('session_highlights', models.TextField(help_text='What did you like most in this session?')),
                ('improvement_suggestions', models.TextField(help_text='What can be improved in the next session?')),
                ('additional_suggestions', models.TextField(blank=True, help_text='Do you have any suggestions? (optional)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actual_session', models.ForeignKey(help_text='Reference to the conducted session', on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback', to='class.actualsession')),
            ],
            options={
                'verbose_name': 'Student Feedback',
                'verbose_name_plural': 'Student Feedback',
                'ordering': ['-submitted_at'],
                'unique_together': {('actual_session', 'anonymous_student_id')},
            },
        ),
        migrations.CreateModel(
            name='TeacherFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_engagement', models.CharField(choices=[('highly', 'Highly'), ('moderate', 'Moderate'), ('low', 'Low')], help_text='Was the class engaged?', max_length=20)),
                ('session_completion', models.CharField(choices=[('yes', 'Yes'), ('partly', 'Partly'), ('no', 'No')], help_text='Was the session completed as planned?', max_length=20)),
                ('student_struggles', models.TextField(help_text='Which part students struggled with most?')),
                ('successful_elements', models.TextField(help_text='What worked well in this session?')),
                ('improvement_areas', models.TextField(help_text='What should be improved for next time?')),
                ('resource_needs', models.TextField(blank=True, help_text='Any support/resources required? (optional)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('actual_session', models.ForeignKey(help_text='Reference to the conducted session', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_feedback', to='class.actualsession')),
                ('facilitator', models.ForeignKey(help_text='Who provided the feedback', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Feedback',
                'verbose_name_plural': 'Teacher Feedback',
                'ordering': ['-submitted_at'],
                'unique_together': {('actual_session', 'facilitator')},
            },
        ),
    ]
