# Generated by Django 5.1.15 on 2026-01-05 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0019_add_comprehensive_feedback_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumsession',
            name='fallback_to_static',
            field=models.BooleanField(default=False, help_text='Force fallback to static content for this day/language'),
        ),
        migrations.AddField(
            model_name='curriculumsession',
            name='is_active_for_facilitators',
            field=models.BooleanField(default=True, help_text='Whether facilitators should see this content'),
        ),
        migrations.AddField(
            model_name='curriculumsession',
            name='last_accessed',
            field=models.DateTimeField(blank=True, help_text='Last time content was accessed by a facilitator', null=True),
        ),
        migrations.AddField(
            model_name='curriculumsession',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times accessed by facilitators'),
        ),
        migrations.AlterField(
            model_name='sessionusagelog',
            name='session',
            field=models.ForeignKey(help_text='Reference to accessed session', on_delete=django.db.models.deletion.CASCADE, related_name='session_usage_logs', to='class.curriculumsession'),
        ),
        migrations.CreateModel(
            name='CurriculumUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_duration', models.PositiveIntegerField(blank=True, help_text='Time spent viewing content in seconds', null=True)),
                ('content_source', models.CharField(choices=[('admin_managed', 'Admin Managed'), ('static_fallback', 'Static Fallback')], help_text='Source of the curriculum content', max_length=20)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_accesses', to='class.classsection')),
                ('curriculum_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_usage_logs', to='class.curriculumsession')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_accesses', to=settings.AUTH_USER_MODEL)),
                ('planned_session', models.ForeignKey(blank=True, help_text='Associated PlannedSession if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='class.plannedsession')),
            ],
            options={
                'verbose_name': 'Curriculum Usage Log',
                'verbose_name_plural': 'Curriculum Usage Logs',
                'ordering': ['-access_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SessionContentMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_source', models.CharField(choices=[('admin_managed', 'Admin Managed'), ('static_fallback', 'Static Fallback'), ('not_available', 'Not Available')], default='static_fallback', max_length=20)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('outdated', 'Outdated'), ('failed', 'Failed')], default='synced', max_length=20)),
                ('curriculum_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_mappings', to='class.curriculumsession')),
                ('planned_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_mapping', to='class.plannedsession')),
            ],
            options={
                'verbose_name': 'Session Content Mapping',
                'verbose_name_plural': 'Session Content Mappings',
            },
        ),
    ]
