# Generated by Django 5.1.15 on 2026-01-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0020_curriculum_integration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsection',
            options={'ordering': ['school__name', 'class_level', 'section'], 'verbose_name': 'Class Section', 'verbose_name_plural': 'Class Sections'},
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='schools/logos/'),
        ),
    ]
