# Generated by Django 5.1.15 on 2026-01-10 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0021_add_school_details_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('date_type', models.CharField(choices=[('session', 'Planned Session'), ('holiday', 'Holiday / No Session'), ('office_work', 'Office Work / Task')], default='session', max_length=20)),
                ('holiday_name', models.CharField(blank=True, help_text='Name of holiday (e.g., Diwali, Summer Break)', max_length=200)),
                ('office_task_description', models.TextField(blank=True, help_text='Description of office work/task')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_sessions', to='class.classsection')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='class.supervisorcalendar')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OfficeWorkAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='class.calendardate')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_work_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['calendar_date', 'facilitator'], name='class_offic_calenda_73b1a4_idx'), models.Index(fields=['facilitator', 'recorded_at'], name='class_offic_facilit_6ae1e4_idx')],
                'unique_together': {('calendar_date', 'facilitator')},
            },
        ),
        migrations.AddIndex(
            model_name='calendardate',
            index=models.Index(fields=['calendar', 'date'], name='class_calen_calenda_626d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendardate',
            index=models.Index(fields=['date_type'], name='class_calen_date_ty_1cd455_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendardate',
            unique_together={('calendar', 'date')},
        ),
    ]
