# Generated by Django 5.1.15 on 2026-01-10 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0022_supervisorcalendar_calendardate_officeworkattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardate',
            name='assigned_facilitators',
            field=models.ManyToManyField(blank=True, help_text='Facilitators assigned to this office work', related_name='assigned_office_work_dates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendardate',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='class.school'),
        ),
        migrations.AddField(
            model_name='calendardate',
            name='time',
            field=models.TimeField(blank=True, help_text='Time for the session/office work', null=True),
        ),
    ]
