# Generated by Django 5.1.15 on 2026-01-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0023_calendardate_assigned_facilitators_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendardate',
            unique_together={('calendar', 'date', 'class_section')},
        ),
        migrations.AddIndex(
            model_name='calendardate',
            index=models.Index(fields=['calendar', 'date', 'class_section'], name='class_calen_calenda_ee83b5_idx'),
        ),
    ]
