# Generated by Django 5.1.15 on 2026-01-10 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0024_alter_calendardate_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitatorTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('facebook_link', 'Facebook Link')], default='photo', max_length=20)),
                ('media_file', models.FileField(blank=True, help_text='Photo or video file', null=True, upload_to='facilitator_tasks/%Y/%m/%d/')),
                ('facebook_link', models.URLField(blank=True, help_text='Facebook post or video link', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the task/preparation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_tasks', to='class.actualsession')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actual_session', 'facilitator'], name='class_facil_actual__c784d2_idx'), models.Index(fields=['facilitator', '-created_at'], name='class_facil_facilit_5125c4_idx')],
            },
        ),
    ]
