# Generated by Django 5.1.15 on 2026-01-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0026_add_facilitator_attendance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='actualsession',
            name='as_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='actualsession',
            name='as_fac_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='actualsession',
            name='as_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='actualsession',
            name='as_ps_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='att_as_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='att_enroll_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='att_status_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='classsection',
            name='cs_school_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enroll_school_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='plannedsession',
            name='ps_class_day_idx',
        ),
        migrations.RemoveIndex(
            model_name='plannedsession',
            name='ps_class_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='st_enroll_num_idx',
        ),
    ]
