# Generated by Django 5.1.15 on 2026-01-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0026_add_performance_indexes_safe'),
        ('class', '0027_remove_actualsession_as_date_idx_and_more'),
    ]

    operations = [
    ]
