# Generated by Django 5.1.15 on 2026-01-12 06:25
# PHASE 1 OPTIMIZATION: Convert status fields from CharField to SmallIntegerField

from django.db import migrations, models


def convert_actualsession_status(apps, schema_editor):
    """Convert ActualSession status from CharField to SmallIntegerField"""
    ActualSession = apps.get_model('class', 'ActualSession')
    status_map = {
        'conducted': 1,
        'holiday': 2,
        'cancelled': 3,
    }
    for session in ActualSession.objects.all():
        if session.status in status_map:
            session.status = status_map[session.status]
            session.save(update_fields=['status'])


def convert_attendance_status(apps, schema_editor):
    """Convert Attendance status from CharField to SmallIntegerField"""
    Attendance = apps.get_model('class', 'Attendance')
    status_map = {
        'present': 1,
        'absent': 2,
        'leave': 3,
    }
    for attendance in Attendance.objects.all():
        if attendance.status in status_map:
            attendance.status = status_map[attendance.status]
            attendance.save(update_fields=['status'])


def convert_calendardate_type(apps, schema_editor):
    """Convert CalendarDate date_type from CharField to SmallIntegerField"""
    CalendarDate = apps.get_model('class', 'CalendarDate')
    type_map = {
        'session': 1,
        'holiday': 2,
        'office_work': 3,
    }
    for date in CalendarDate.objects.all():
        if date.date_type in type_map:
            date.date_type = type_map[date.date_type]
            date.save(update_fields=['date_type'])


def convert_curriculum_status(apps, schema_editor):
    """Convert CurriculumSession status from CharField to SmallIntegerField"""
    CurriculumSession = apps.get_model('class', 'CurriculumSession')
    status_map = {
        'draft': 1,
        'published': 2,
        'archived': 3,
    }
    for session in CurriculumSession.objects.all():
        if session.status in status_map:
            session.status = status_map[session.status]
            session.save(update_fields=['status'])


def reverse_all(apps, schema_editor):
    """Reverse all conversions"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0028_grouped_session_support'),
    ]

    operations = [
        # Step 1: Convert data from string to integer
        migrations.RunPython(convert_actualsession_status, reverse_all),
        migrations.RunPython(convert_attendance_status, reverse_all),
        migrations.RunPython(convert_calendardate_type, reverse_all),
        migrations.RunPython(convert_curriculum_status, reverse_all),
        
        # Step 2: Add new denormalized fields to Attendance
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Cached from enrollment.student_id', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_section_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Cached from enrollment.class_section_id', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='school_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Cached from enrollment.school_id', null=True),
        ),
        
        # Step 3: Alter field types from CharField to SmallIntegerField
        migrations.AlterField(
            model_name='actualsession',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Conducted'), (2, 'Holiday'), (3, 'Cancelled')], default=1, help_text='Session status: 1=Conducted, 2=Holiday, 3=Cancelled'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Present'), (2, 'Absent'), (3, 'Leave')], default=1, help_text='Attendance status: 1=Present, 2=Absent, 3=Leave'),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='date_type',
            field=models.SmallIntegerField(choices=[(1, 'Planned Session'), (2, 'Holiday / No Session'), (3, 'Office Work / Task')], default=1, help_text='Type: 1=Session, 2=Holiday, 3=Office Work'),
        ),
        migrations.AlterField(
            model_name='curriculumsession',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Archived')], default=1, help_text='Status: 1=Draft, 2=Published, 3=Archived'),
        ),
        
        # Step 4: Add indexes
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['is_active', 'school'], name='enroll_active_sch_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'is_active'], name='enroll_stud_active_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status', 'marked_at'], name='attend_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student_id', 'marked_at'], name='attend_stud_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_section_id', 'marked_at'], name='attend_cls_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['school_id', 'marked_at'], name='attend_sch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='actualsession',
            index=models.Index(fields=['planned_session', 'status'], name='asess_sess_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='actualsession',
            index=models.Index(fields=['date', 'status'], name='asess_date_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='actualsession',
            index=models.Index(fields=['facilitator', 'date'], name='asess_facil_date_idx'),
        ),
        migrations.AddIndex(
            model_name='actualsession',
            index=models.Index(fields=['status', 'date'], name='asess_stat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calendardate',
            index=models.Index(fields=['calendar', 'date'], name='caldate_cal_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calendardate',
            index=models.Index(fields=['date_type', 'date'], name='caldate_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calendardate',
            index=models.Index(fields=['school', 'date'], name='caldate_sch_date_idx'),
        ),
        migrations.AddIndex(
            model_name='studentperformance',
            index=models.Index(fields=['student', 'subject'], name='perf_stud_subj_idx'),
        ),
        migrations.AddIndex(
            model_name='studentperformance',
            index=models.Index(fields=['class_section', 'subject'], name='perf_cls_subj_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitatorschool',
            index=models.Index(fields=['is_active', 'school'], name='facsch_active_sch_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitatorschool',
            index=models.Index(fields=['facilitator', 'is_active'], name='facsch_facil_active_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionusagelog',
            index=models.Index(fields=['session', 'facilitator'], name='suslog_sess_facil_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionusagelog',
            index=models.Index(fields=['facilitator', 'access_timestamp'], name='suslog_facil_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumusagelog',
            index=models.Index(fields=['curriculum_session', 'facilitator'], name='culog_curr_facil_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumusagelog',
            index=models.Index(fields=['facilitator', 'access_timestamp'], name='culog_facil_ts_idx'),
        ),
    ]
