# Generated by Django 5.1.15 on 2026-01-12 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0030_remove_actualsession_class_actua_planned_f63c56_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('school_shutdown', 'School permanently shuts down for this class'), ('syllabus_change', 'Government removes topic from syllabus'), ('exam_period', 'Exam period replaces class permanently'), ('duplicate_session', 'Duplicate or wrongly created planned session'), ('emergency', 'Emergency where session will never happen again')], help_text='Why session was cancelled', max_length=50)),
                ('category', models.CharField(blank=True, help_text='Cancellation category', max_length=50)),
                ('is_permanent', models.BooleanField(default=False, help_text='Cannot be undone')),
                ('can_be_rescheduled', models.BooleanField(default=True, help_text='Can be rescheduled')),
                ('change_reason', models.TextField(blank=True, help_text='Why status was changed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_session', models.OneToOneField(help_text='Reference to the cancelled session', on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='class.actualsession')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Who changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_cancellations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Cancellation',
                'verbose_name_plural': 'Session Cancellations',
                'indexes': [models.Index(fields=['actual_session', 'is_permanent'], name='scancel_sess_perm_idx')],
            },
        ),
    ]
