# Generated by Django 5.1.15 on 2026-01-12 08:45

from django.db import migrations


def migrate_cancellation_data(apps, schema_editor):
    """
    Migrate cancellation data from ActualSession to SessionCancellation
    Only for sessions with status = CANCELLED (3)
    """
    ActualSession = apps.get_model('class', 'ActualSession')
    SessionCancellation = apps.get_model('class', 'SessionCancellation')
    
    # Find all cancelled sessions
    cancelled_sessions = ActualSession.objects.filter(status=3)  # CANCELLED
    
    count = 0
    for session in cancelled_sessions:
        # Create cancellation record with all data
        SessionCancellation.objects.create(
            actual_session=session,
            reason=session.cancellation_reason or 'emergency',
            category=session.cancellation_category or '',
            is_permanent=session.is_permanent_cancellation,
            can_be_rescheduled=session.can_be_rescheduled,
            changed_by=session.status_changed_by,
            change_reason=session.status_change_reason or ''
        )
        count += 1
    
    print(f"✅ Migrated {count} cancellation records")


def reverse_migration(apps, schema_editor):
    """
    Reverse: Delete all SessionCancellation records
    ActualSession data remains intact
    """
    SessionCancellation = apps.get_model('class', 'SessionCancellation')
    count = SessionCancellation.objects.count()
    SessionCancellation.objects.all().delete()
    print(f"✅ Deleted {count} cancellation records (rollback)")


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0031_sessioncancellation'),
    ]

    operations = [
        migrations.RunPython(migrate_cancellation_data, reverse_migration),
    ]
