# Generated by Django 5.1.15 on 2026-01-12 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0032_migrate_cancellation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedsession',
            name='content_version',
            field=models.PositiveIntegerField(default=1, help_text='Version of curriculum content'),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='curriculum_session',
            field=models.ForeignKey(blank=True, help_text='Linked curriculum content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_sessions', to='class.curriculumsession'),
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='last_content_sync',
            field=models.DateTimeField(blank=True, help_text='When content was last synced', null=True),
        ),
    ]
