# Generated by Django 5.1.15 on 2026-01-13 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0033_plannedsession_content_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitatortask',
            name='actual_session',
            field=models.ForeignKey(blank=True, help_text='Optional - task can be created without a session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_tasks', to='class.actualsession'),
        ),
    ]
