# Generated by Django 5.1.15 on 2026-01-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0034_make_facilitator_task_session_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=28.7041, help_text='School latitude coordinate', max_digits=9),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=77.1025, help_text='School longitude coordinate', max_digits=9),
        ),
    ]
