# Generated by Django 5.1.15 on 2026-01-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0035_school_latitude_school_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(default='Madhya Pradesh', help_text='State/Province', max_length=100),
        ),
    ]
