# Generated by Django 5.1.15 on 2026-01-22 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0036_school_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Cluster/Area name', max_length=200, unique=True)),
                ('district', models.CharField(help_text='District this cluster belongs to', max_length=100)),
                ('state', models.CharField(default='Madhya Pradesh', help_text='State/Province', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the cluster', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Cluster center latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Cluster center longitude', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'ordering': ['district', 'name'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='cluster',
            field=models.ForeignKey(blank=True, help_text='Cluster/Area this school belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='class.cluster'),
        ),
    ]
